const projects = [
    {
        id: 'autoverse-rental',
        thumbnail: '/autoverse/Autoverse rental car website.png',
        images: [
            '/autoverse/Autoverse rental car website.png',
            '/autoverse/Autoverse rental car.png',
            '/autoverse/Autoverse rental car calls.png',
            '/autoverse/Autoverse rental car overivew views.png',
            '/autoverse/Autoverse rental car Website click.png'
        ],
        tag: 'Local SEO & GBP',
        Title: 'Autoverse Rental Car Website desing and Local SEO',
        Client: 'Autoverse',
        Duration: '3 months',
        Focus: 'UX & Customers calls',
        'Organic Visits': '650+/mo',
        'Keyword ranking': '#1 for "Luxury Car Rental"',
        'Revenue from Organic': '$50,000+/mo',
        'Domain Authority': 'N/A',
        'Project overview': 'Developed a high-conversion website and executed a complete SEO and Local SEO strategy for Autoverse Rental Car to improve online visibility, local rankings, booking inquiries, and consistent Google Rankings.',
        'the challenge': 'There was no professionally built website to support online bookings, organic visibility was low with a weak local search presence, and a poorly optimized Google Business Profile was limiting calls and customer inquiries.',
        'The Solution': 'Designed and developed a responsive, user-friendly website focused on lead generation, created and optimized service and location-focused pages using SEO best practices, fully optimized the Google Business Profile including categories, services, descriptions, and images, implemented on-page SEO with internal linking and local keyword targeting, and set up tracking to monitor traffic, calls, and overall performance.',
        review: "Excellent service that greatly improved our online visibility and increased calls. Professional, efficient, and highly recommended.",
        reviewer: "James Wilson",
        "reviewer designation": "Business Owner"
    },
    {
        id: 'kritical-towing',
        thumbnail: '/Kritical Towing/Kritical towing website.png',
        images: [
            '/Kritical Towing/Kritical towing website.png',
            '/Kritical Towing/Kritical towing calls.png',
            '/Kritical Towing/Kritical towing overview views.png',
            '/Kritical Towing/Kritical towing overview.png'
        ],
        tag: 'Google Business Profile & Local SEO',
        Title: 'Kritical Towing - Local SEO Dominance',
        Client: 'Kritical Towing',
        Duration: '4 months',
        Focus: 'Local SEO & GMB',
        'Organic Views': '5000+',
        'Keyword ranking': 'Top 3 Map Pack',
        'Revenue from Organic': '$20,000/mo',
        'Domain Authority': '0',
        'Project overview': 'Redesigned the website and implemented a targeted Local SEO strategy for Kritical Towing to improve local search visibility, Google Maps presence, and inbound towing calls.',
        'the challenge': 'The website was outdated with a poor user experience and low conversions, local visibility for towing-related keywords was weak, and inbound leads from organic and local search were limited.',
        'The Solution': 'Redesigned the website with a mobile-first, conversion-focused structure, optimized service pages using high-intent local towing keywords, implemented on-page local SEO with internal linking and location signals, improved technical SEO to support indexing, speed, and performance, and set up tracking to measure local traffic and lead performance.',
        review: "Fantastic results overall. Our website performance and local visibility improved quickly, leading to more consistent leads. The process was smooth, professional, and delivered exactly what was promised.",
        reviewer: "Sarah Jenkins",
        "reviewer designation": "Owner"
    },
    {
        id: 'malibu-gutters',
        thumbnail: '/malibu/Malibu gutters website.png',
        images: [
            '/malibu/Malibu gutters website.png',
            '/malibu/Malibu calls.png',
            '/malibu/Malibu gutters overview views.png',
            '/malibu/Malibu gutters overview.png',
            '/malibu/Malibu gutters website clicks.png'
        ],
        tag: 'GBP & Local SEO',
        Title: 'Malibu Gutters - SEO & Lead Gen Optimization',
        Client: 'Malibu Gutters',
        Duration: '1 months',
        Focus: 'Lead Generation',
        'Organic Traffic': '1500+',
        'Keyword ranking': '#1 "Gutter Repair"',
        'Revenue from Organic': '$5,000/in first month',
        'Domain Authority': 'N/A',
        'Project overview': 'Developed a high-conversion website and executed a complete SEO and Local SEO strategy for Malibu Gutters to improve local search visibility, Google Maps rankings, and inbound service inquiries.',
        'the challenge': 'There was no professionally developed website to support lead generation, organic and local visibility for gutter service keywords was low, and an under-optimized Google Business Profile was limiting local reach.',
        'The Solution': 'Designed and developed a mobile-first, fast-loading website focused on conversions, created and optimized service and location pages using local SEO best practices, fully optimized the Google Business Profile including categories, services, descriptions, and images, implemented on-page SEO with internal linking and local ranking signals, and improved technical SEO to support indexing, speed, and overall performance.',
        review: "The website and local presence improvements led to faster performance, better visibility, and more leads. Very satisfied with the results.",
        reviewer: "Mike Roberts",
        "reviewer designation": "Business owner"
    },
    {
        id: 'patriot-towing',
        thumbnail: '/Patriot towing/Patriots towing website.png',
        images: [
            '/Patriot towing/Patriots towing website.png',
            '/Patriot towing/Patriots towing Calls.png',
            '/Patriot towing/Patriots towing overview views.png',
            '/Patriot towing/Patriots towing overview.png',
            '/Patriot towing/Patriots towing website clicks.png'
        ],
        tag: 'Local SEO & Branding',
        Title: 'Patriot Towing - Brand & Visibility Scale',
        Client: 'Patriot Towing',
        Duration: '3 months',
        Focus: 'Local SEO & Calls Conversion',
        'Organic Visits': '1600+',
        'Keyword ranking': '#1 "Towing near me"',
        'Revenue from Organic': '$10,000/mo',
        'Domain Authority': '0',
        'Project overview': 'Redesigned the website and implemented a focused Local SEO strategy for Patriots Towing to improve local search visibility, increase Google Maps presence, and drive more inbound towing calls.',
        'the challenge': 'The website was outdated with poor user experience and low conversions, local search visibility for towing-related keywords was weak, and inbound leads from organic and local search were limited.',
        'The Solution': 'Redesigned the website with a mobile-first, conversion-focused structure, optimized service pages with high-intent local towing keywords, implemented on-page local SEO with internal linking and location signals, improved technical SEO to support crawling, indexing, and speed, and set up tracking to measure local traffic and lead performance.',
        review: "The updates greatly improved website performance, local visibility, and lead generation. Very effective and results-driven.",
        reviewer: "David Anderson",
        "reviewer designation": "Owner"
    },
    {
        id: 'w-towing',
        thumbnail: '/W towing/W towing overview website.png',
        images: [
            '/W towing/W towing overview website.png',
            '/W towing/W towing calls.png',
            '/W towing/W towing Directions.png',
            '/W towing/W towing overview overview views.png',
            '/W towing/W towing overview.png',
            '/W towing/W towing Website click.png'
        ],
        tag: 'Emergency Services',
        Title: 'W Towing - 24/7 Response Optimization',
        Client: 'W Towing',
        Duration: '3 months',
        Focus: 'Speed & Mobile UX',
        'Organic Traffic': '7900+',
        'Keyword ranking': '#2 Map Pack',
        'Revenue from Organic': '$20,000/mo',
        'Domain Authority': '31',
        'Project overview': 'Designed a conversion-focused website and implemented a complete SEO and Local SEO strategy for W Towing to improve online visibility, Google Maps rankings, and inbound call volume.',
        'the challenge': 'There was no professionally designed website to support conversions, organic rankings for towing-related keywords were low, and an under-optimized Google Business Profile was limiting local reach.',
        'The Solution': 'Designed and developed a mobile-first, fast-loading website focused on lead generation, optimized service pages using high-intent local towing keywords, fully optimized the Google Business Profile including categories, services, descriptions, and images, and implemented on-page SEO with internal linking and local ranking signals.',
        review: "The updates significantly improved website speed, local visibility, and lead generation. Very satisfied with the results.",
        reviewer: "Greg Thompson",
        "reviewer designation": "Business owner"
    },
    {
        id: 'moore-sturgis',
        thumbnail: '/moore and sturgis/Moore and sturgis website Clicks.png',
        images: [
            '/moore and sturgis/Moore and sturgis website Clicks.png',
            '/moore and sturgis/Moore and sturgis Calls.png',
            '/moore and sturgis/Moore and sturgis directions.png',
            '/moore and sturgis/Moore and sturgis overview views.png',
            '/moore and sturgis/Moore and sturgis overview.png'
        ],
        tag: 'Local SEO & GBP',
        Title: 'Moore & Sturgis - Professional Authority',
        Client: 'Moore & Sturgis',
        Duration: '4 months',
        Focus: 'Authority & Trust',
        'Organic Traffic': '1,800/mo',
        'Keyword ranking': 'First Page "Legal Firm"',
        'Revenue from Organic': '$65,000/mo',
        'Domain Authority': '40',
        'Project overview': 'Implemented a targeted Local SEO and Google Business Profile optimization strategy for Moore and Sturgis to improve Google Maps visibility, attract high-intent local customers, and increase service inquiries.',
        'the challenge': 'Visibility in Google Maps for auto body repair keywords was low, the Google Business Profile was under-optimized, and inbound calls and direction requests from local search were limited.',
        'The Solution': 'Fully optimized the Google Business Profile including categories, services, description, and attributes, implemented local keyword optimization for auto body and collision repair services, improved service area and business information accuracy, added optimized images to enhance engagement and trust, and applied ongoing optimization best practices to improve rankings and visibility.',
        review: "Local visibility and engagement improved significantly, leading to more calls and inquiries. Very pleased with the results.",
        reviewer: "Elizabeth Moore",
        "reviewer designation": "Business Owner"
    },
    {
        id: 'austin-dumpster',
        thumbnail: '/Austin Dumpster/Austin Dumpster website.png',
        images: [
            '/Austin Dumpster/Austin Dumpster website.png',
            '/Austin Dumpster/Austin dumpster calls.png',
            '/Austin Dumpster/Austin dumpster overview views.png',
            '/Austin Dumpster/Austin dumpster overview.png',
            '/Austin Dumpster/Austin dumpster website click.png'
        ],
        tag: 'Local SEO & GBP',
        Title: 'Austin Dumpster - Local Market Takeover',
        Client: 'Austin Dumpster',
        Duration: '3 months',
        Focus: 'Hyper-Local SEO',
        'Organic Traffic': '2300+',
        'Keyword ranking': '#1 "Dumpster Rental"',
        'Revenue from Organic': '$20,000/mo',
        'Domain Authority': '36',
        'Project overview': 'Redesigned the website and executed a complete SEO and Local SEO strategy for Austin Dumpster to increase local search visibility, improve lead quality, and drive consistent inbound inquiries.',
        'the challenge': 'The website was outdated with poor structure and low conversion rates, organic visibility for dumpster rental keywords was limited, and the Google Business Profile was under-optimized, affecting local rankings.',
        'The Solution': 'Redesigned the website with a clean, mobile-first, conversion-focused layout, optimized service and location pages using targeted local SEO keywords, fully optimized the Google Business Profile including categories, services, descriptions, and images, implemented on-page SEO with internal linking and local ranking signals, and improved technical SEO to support indexing and overall performance.',
        review: "The website and local presence improvements boosted visibility, engagement, and leads. Very satisfied with the outcome.",
        reviewer: "Robert Chen",
        "reviewer designation": "Business Owner"
    },
    {
        id: 'amar-towing',
        thumbnail: '/amar towing/amar towing website.png',
        images: [
            '/amar towing/amar towing website.png',
            '/amar towing/AMAR towing Calls.png',
            '/amar towing/Amar towing Directions.png',
            '/amar towing/Amar towing overview views.png',
            '/amar towing/Amar towing overview.png'
        ],
        tag: 'Local SEO & GBP',
        Title: 'Amar Towing - Rapid Response UI',
        Client: 'Amar Towing',
        Duration: '3 months',
        Focus: 'User Interface',
        'Organic Traffic': '2300+',
        'Keyword ranking': '#3 "Tow Truck Near Me"',
        'Revenue from Organic': '$38,000/mo',
        'Domain Authority': 'N/A',
        'Project overview': 'Redesigned the website and implemented a complete Local SEO strategy for Amar Towing to improve local visibility, lead generation, and Google Maps rankings. The project focused on conversion optimization, growth of GBP, and location-based keyword targeting.',
        'the challenge': 'The website was outdated, delivered a poor user experience, and generated low conversions, while Google Business Profile visibility was weak and local towing-related keywords ranked poorly in search results.',
        'The Solution': 'The website was fully redesigned with a mobile-first, conversion-focused layout, service pages were optimized with local keywords and clear CTAs, the Google Business Profile was optimized and managed, a local SEO strategy was implemented with on-page optimization and location signals, and NAP consistency and internal linking were improved to support local rankings.',
        review: "Clean, professional, and effective. Exactly what we needed.",
        reviewer: "Amar Singh",
        "reviewer designation": "Business Owner"
    },
    {
        id: 'atlanta-services',
        thumbnail: '/atlanta/Atlanta Mobile Tire Shop.png',
        images: [
            '/atlanta/Atlanta Mobile Tire Shop.png',
            '/atlanta/Atlanta Mobile Tire Shop calls.png',
            '/atlanta/Atlanta Mobile Tire Shop overview views.png',
            '/atlanta/Atlanta Mobile Tire Shop Website click.png'
        ],
        tag: 'Local SEO & GBP',
        Title: 'Atlanta Mobile Tire Shop - Regional SEO',
        Client: 'Atlanta Services Co.',
        Duration: '4 months',
        Focus: 'Regional Expansion',
        'Organic Traffic': '11500+',
        'Keyword ranking': 'Top 5 Metro-wide',
        'Revenue from Organic': '$75,000/mo',
        'Domain Authority': 'N/A',
        'Project overview': 'Redesigned the website and executed a complete SEO and Local SEO strategy for a Mobile Tire Shop to improve local search visibility, Google Maps rankings, and inbound service calls for on-site tire services.',
        'the challenge': 'The website was outdated with a poor structure and low conversions, organic visibility for mobile tire service keywords was limited, and the Google Business Profile was under-optimized, negatively affecting local reach.',
        'The Solution': 'The website was redesigned with a mobile-first, conversion-focused layout, service pages were optimized with high-intent local and mobile service keywords, the Google Business Profile was fully optimized, on-page SEO, internal linking, and local ranking signals were implemented, and technical SEO was improved to support indexing, speed, and performance.',
        review: "We are now competing with the biggest names in Atlanta.",
        reviewer: "Kevin Durrant",
        "reviewer designation": "Business Owner"
    },
    {
        id: 'automotive-perfection',
        thumbnail: '/automotive/Automotive perfection Website.png',
        images: [
            '/automotive/Automotive perfection Website.png',
            '/automotive/Automotive perfection calls.png',
            '/automotive/Automotive perfection overview views.png',
            '/automotive/Automotive perfection overview.png',
            '/automotive/Automotive perfection website directions.png'
        ],
        tag: 'Automotive Repair',
        Title: 'Automotive Perfection - Service Optimization',
        Client: 'Automotive Perfection',
        Duration: '4 months',
        Focus: 'Service Conversions',
        'Organic Traffic': '5,000/mo',
        'Keyword ranking': '#1 "Engine Repair"',
        'Revenue from Organic': '$60,000/mo',
        'Domain Authority': '25',
        'Project overview': 'Implemented a comprehensive Website SEO and Google Business Profile optimization strategy for Automotive Perfection to improve local search visibility, Google Maps rankings, and inbound service inquiries for both auto repair and auto detailing services.',
        'the challenge': 'Organic visibility for auto repair and auto detailing keywords was low, the Google Business Profile was under-optimized and negatively impacted Maps rankings, and the website was not fully optimized to capture local service traffic.',
        'The Solution': 'The website service pages were optimized for auto repair and auto detailing keywords, on-page SEO, internal linking, and local relevance signals were improved, the Google Business Profile was fully optimized, local keyword targeting was implemented for both repair and detailing services, and technical SEO elements were improved to support indexing and performance.',
        review: "We are booked solid for three weeks out. The website is doing the selling for us.",
        reviewer: "Tom Hardy",
        "reviewer designation": "Business Owner"
    },
    {
        id: 'listings-management',
        thumbnail: '/Listings/Bing Places for Business Dashboard.png',
        images: [
            '/Listings/Bing Places for Business Dashboard.png',
            '/Listings/apple maps listing.png',
            '/Listings/Bing Places for Business.png'
        ],
        tag: 'Citaitons & Business Lisitng',
        Title: 'Strategic Listings & GBP Optimization',
        Client: 'Various Local Businesses',
        Duration: '1 month',
        Focus: 'Local SEO & AI visibility',
        'Organic Traffic': '25,000/mo (Aggregated)',
        'Keyword ranking': '',
        'Revenue from Organic': '+$200k Impact overall',
        'Domain Authority': 'N/A',
        'Project overview': 'A comprehensive approach to managing and optimizing listings across 50+ directories including Google, Bing, and Yelp.',
        'the challenge': 'Businesses need business listings on some of the strongest directories to improve their visibility and rankings.',
        'The Solution': 'Lsited Businesses across multiple highest directories (including Apple maps and Bing) and optimized the listings.',
        review: "Apple maps experience is rere as we have seen.",
        reviewer: "Maria Rodriguez",
        "reviewer designation": "Marketing Mgr"
    }
];

export default projects;
